# Generated by Django 4.2.4 on 2023-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidato',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('img_candidato', models.ImageField(upload_to='./candidatos/')),
                ('cantidad_de_votos', models.IntegerField(default=0)),
            ],
        ),
    ]
